# Generated by Django 5.0.7 on 2024-08-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financas', '0002_alter_transacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
