# Generated by Django 5.0.7 on 2024-08-04 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financas', '0004_alter_transacao_descricao_alter_transacao_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldosFaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_bradesco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_itau', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_inter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fatura_bradesco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fatura_itau', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fatura_inter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
