# Generated by Django 5.0.7 on 2024-08-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_financas', '0005_saldosfaturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldosfaturas',
            name='user',
        ),
    ]
